import { FontDef } from './types';

export const GOOGLE_FONTS_LIST: FontDef[] = [
  // SANS-SERIF
  { family: 'Roboto', category: 'sans-serif', tags: ['minimal', 'standard'] },
  { family: 'Open Sans', category: 'sans-serif', tags: ['minimal', 'clean'] },
  { family: 'Montserrat', category: 'sans-serif', tags: ['minimal', 'modern'] },
  { family: 'Lato', category: 'sans-serif', tags: ['minimal'] },
  { family: 'Poppins', category: 'sans-serif', tags: ['modern', 'friendly'] },
  { family: 'Source Sans Pro', category: 'sans-serif', tags: ['standard'] },
  { family: 'Inter', category: 'sans-serif', tags: ['minimal', 'tech'] },
  { family: 'Oswald', category: 'sans-serif', tags: ['brutal', 'condensed'] },
  { family: 'Raleway', category: 'sans-serif', tags: ['elegant', 'thin'] },
  { family: 'Noto Sans', category: 'sans-serif', tags: ['standard'] },
  { family: 'Ubuntu', category: 'sans-serif', tags: ['modern', 'friendly'] },
  { family: 'Nunito', category: 'sans-serif', tags: ['playful', 'rounded'] },
  { family: 'Rubik', category: 'sans-serif', tags: ['modern', 'friendly'] },
  { family: 'Work Sans', category: 'sans-serif', tags: ['minimal', 'modern'] },
  { family: 'Quicksand', category: 'sans-serif', tags: ['playful', 'rounded'] },
  { family: 'DM Sans', category: 'sans-serif', tags: ['minimal', 'modern'] },
  { family: 'Josefin Sans', category: 'sans-serif', tags: ['elegant', 'retro'] },
  { family: 'Dosis', category: 'sans-serif', tags: ['playful', 'modern'] },
  { family: 'Anton', category: 'sans-serif', tags: ['brutal', 'loud'] },
  { family: 'Fjalla One', category: 'sans-serif', tags: ['brutal', 'condensed'] },
  { family: 'Chakra Petch', category: 'sans-serif', tags: ['cyber', 'tech'] },
  { family: 'Orbitron', category: 'sans-serif', tags: ['cyber', 'futuristic'] },
  { family: 'Exo 2', category: 'sans-serif', tags: ['cyber', 'futuristic'] },
  { family: 'Teko', category: 'sans-serif', tags: ['brutal', 'condensed'] },
  { family: 'Russo One', category: 'sans-serif', tags: ['cyber', 'brutal'] },
  { family: 'Kanit', category: 'sans-serif', tags: ['modern', 'heavy'] },
  { family: 'Heebo', category: 'sans-serif', tags: ['minimal', 'clean'] },
  { family: 'Arimo', category: 'sans-serif', tags: ['standard'] },
  { family: 'Muli', category: 'sans-serif', tags: ['minimal'] },
  { family: 'Karla', category: 'sans-serif', tags: ['quirky', 'minimal'] },
  { family: 'Cabin', category: 'sans-serif', tags: ['modern', 'soft'] },
  { family: 'Oxygen', category: 'sans-serif', tags: ['clean', 'minimal'] },
  { family: 'Titillium Web', category: 'sans-serif', tags: ['tech', 'geometric'] },
  { family: 'PT Sans', category: 'sans-serif', tags: ['standard'] },
  { family: 'Hind', category: 'sans-serif', tags: ['clean', 'modern'] },
  { family: 'Assistant', category: 'sans-serif', tags: ['minimal'] },
  { family: 'Manrope', category: 'sans-serif', tags: ['modern', 'geometric'] },
  { family: 'Comfortaa', category: 'sans-serif', tags: ['playful', 'rounded'] },
  { family: 'Lexend', category: 'sans-serif', tags: ['minimal', 'clean'] },

  // SERIF
  { family: 'Roboto Slab', category: 'serif', tags: ['sturdy'] },
  { family: 'Playfair Display', category: 'serif', tags: ['elegant', 'luxe'] },
  { family: 'Merriweather', category: 'serif', tags: ['classic', 'book'] },
  { family: 'Lora', category: 'serif', tags: ['elegant', 'classic'] },
  { family: 'Arvo', category: 'serif', tags: ['sturdy', 'retro'] },
  { family: 'Bitter', category: 'serif', tags: ['classic'] },
  { family: 'Cinzel', category: 'serif', tags: ['elegant', 'classic'] },
  { family: 'Cormorant Garamond', category: 'serif', tags: ['elegant', 'luxe'] },
  { family: 'Zilla Slab', category: 'serif', tags: ['sturdy', 'modern'] },
  { family: 'Crimson Text', category: 'serif', tags: ['classic', 'elegant'] },
  { family: 'PT Serif', category: 'serif', tags: ['standard'] },
  { family: 'Noto Serif', category: 'serif', tags: ['standard'] },
  { family: 'Libre Baskerville', category: 'serif', tags: ['classic', 'book'] },
  { family: 'Spectral', category: 'serif', tags: ['elegant', 'modern'] },
  { family: 'Eb Garamond', category: 'serif', tags: ['classic', 'luxe'] },
  { family: 'BioRhyme', category: 'serif', tags: ['weird', 'heavy'] },
  { family: 'Cardo', category: 'serif', tags: ['classic', 'scholarly'] },
  { family: 'Domine', category: 'serif', tags: ['classic', 'sturdy'] },
  { family: 'Old Standard TT', category: 'serif', tags: ['retro', 'classic'] },
  { family: 'Vollkorn', category: 'serif', tags: ['classic', 'warm'] },
  { family: 'Alice', category: 'serif', tags: ['elegant', 'playful'] },
  { family: 'Neuton', category: 'serif', tags: ['minimal', 'serif'] },
  { family: 'Ultra', category: 'serif', tags: ['brutal', 'heavy'] },
  { family: 'Bree Serif', category: 'serif', tags: ['friendly', 'modern'] },

  // MONOSPACE
  { family: 'Inconsolata', category: 'monospace', tags: ['tech', 'minimal'] },
  { family: 'Space Mono', category: 'monospace', tags: ['tech', 'cyber'] },
  { family: 'VT323', category: 'monospace', tags: ['retro', 'tech'] },
  { family: 'Share Tech Mono', category: 'monospace', tags: ['cyber', 'tech'] },
  { family: 'Source Code Pro', category: 'monospace', tags: ['standard', 'tech'] },
  { family: 'Roboto Mono', category: 'monospace', tags: ['standard', 'tech'] },
  { family: 'Fira Code', category: 'monospace', tags: ['tech', 'modern'] },
  { family: 'JetBrains Mono', category: 'monospace', tags: ['tech', 'clean'] },
  { family: 'Ubuntu Mono', category: 'monospace', tags: ['tech', 'friendly'] },
  { family: 'Courier Prime', category: 'monospace', tags: ['retro', 'typewriter'] },
  { family: 'Major Mono Display', category: 'monospace', tags: ['weird', 'minimal'] },
  { family: 'Anonymous Pro', category: 'monospace', tags: ['tech', 'standard'] },
  { family: 'Nova Mono', category: 'monospace', tags: ['weird', 'tech'] },
  { family: 'Cutive Mono', category: 'monospace', tags: ['retro', 'typewriter'] },
  { family: 'IBM Plex Mono', category: 'monospace', tags: ['tech', 'industrial'] },
  { family: 'Red Hat Mono', category: 'monospace', tags: ['tech', 'geometric'] },

  // HANDWRITING
  { family: 'Dancing Script', category: 'handwriting', tags: ['cute', 'fluid'] },
  { family: 'Pacifico', category: 'handwriting', tags: ['retro', 'playful'] },
  { family: 'Shadows Into Light', category: 'handwriting', tags: ['cute', 'sketch'] },
  { family: 'Indie Flower', category: 'handwriting', tags: ['cute', 'sketch'] },
  { family: 'Permanent Marker', category: 'handwriting', tags: ['brutal', 'street'] },
  { family: 'Caveat', category: 'handwriting', tags: ['cute', 'friendly'] },
  { family: 'Satisfy', category: 'handwriting', tags: ['elegant', 'fluid'] },
  { family: 'Great Vibes', category: 'handwriting', tags: ['elegant', 'formal'] },
  { family: 'Gloria Hallelujah', category: 'handwriting', tags: ['cute', 'sketch'] },
  { family: 'Amatic SC', category: 'handwriting', tags: ['cute', 'minimal'] },
  { family: 'Courgette', category: 'handwriting', tags: ['elegant', 'fluid'] },
  { family: 'Kaushan Script', category: 'handwriting', tags: ['rough', 'loud'] },
  { family: 'Sacramento', category: 'handwriting', tags: ['elegant', 'thin'] },
  { family: 'Yellowtail', category: 'handwriting', tags: ['retro', 'fluid'] },
  { family: 'Patrick Hand', category: 'handwriting', tags: ['cute', 'friendly'] },
  { family: 'Homemade Apple', category: 'handwriting', tags: ['sketch', 'organic'] },
  { family: 'Zeyada', category: 'handwriting', tags: ['weird', 'sketch'] },
  { family: 'Rock Salt', category: 'handwriting', tags: ['brutal', 'street'] },
  { family: 'Bad Script', category: 'handwriting', tags: ['cute', 'sketch'] },
  { family: 'Cookie', category: 'handwriting', tags: ['retro', 'elegant'] },

  // DISPLAY
  { family: 'Abril Fatface', category: 'display', tags: ['elegant', 'loud'] },
  { family: 'Bebas Neue', category: 'display', tags: ['brutal', 'impact'] },
  { family: 'Lobster', category: 'display', tags: ['retro', 'playful'] },
  { family: 'Righteous', category: 'display', tags: ['cyber', 'retro'] },
  { family: 'Fredoka One', category: 'display', tags: ['playful', 'cute'] },
  { family: 'Alfa Slab One', category: 'display', tags: ['brutal', 'heavy'] },
  { family: 'Press Start 2P', category: 'display', tags: ['retro', 'gaming'] },
  { family: 'Creepster', category: 'display', tags: ['weird', 'spooky'] },
  { family: 'Nosifer', category: 'display', tags: ['weird', 'spooky'] },
  { family: 'Special Elite', category: 'display', tags: ['retro', 'typewriter'] },
  { family: 'Monoton', category: 'display', tags: ['retro', 'futuristic'] },
  { family: 'Bangers', category: 'display', tags: ['loud', 'comic'] },
  { family: 'Luckiest Guy', category: 'display', tags: ['playful', 'loud'] },
  { family: 'Passion One', category: 'display', tags: ['brutal', 'heavy'] },
  { family: 'Fascinate', category: 'display', tags: ['retro', 'weird'] },
  { family: 'Syncopate', category: 'display', tags: ['minimal', 'futuristic'] },
  { family: 'Faster One', category: 'display', tags: ['retro', 'futuristic'] },
  { family: 'Fugaz One', category: 'display', tags: ['modern', 'retro'] },
  { family: 'Black Ops One', category: 'display', tags: ['brutal', 'stencil'] },
  { family: 'Stardos Stencil', category: 'display', tags: ['retro', 'stencil'] },
  { family: 'Wallpoet', category: 'display', tags: ['cyber', 'stencil'] },
  { family: 'Vast Shadow', category: 'display', tags: ['retro', 'weird'] },
  { family: 'Megrim', category: 'display', tags: ['cyber', 'weird'] },
  { family: 'UnifrakturMaguntia', category: 'display', tags: ['retro', 'gothic'] },
  { family: 'Pirata One', category: 'display', tags: ['gothic', 'brutal'] },
  { family: 'Metal Mania', category: 'display', tags: ['brutal', 'gothic'] },
  { family: 'Shojumaru', category: 'display', tags: ['weird', 'brutal'] },
  { family: 'Ewert', category: 'display', tags: ['weird', 'ornate'] },
  { family: 'Codystar', category: 'display', tags: ['minimal', 'weird'] },
  { family: 'Glass Antiqua', category: 'display', tags: ['retro', 'elegant'] },

  // ADDING MORE FOR THE DOOM SCROLL
  { family: 'Archivo Black', category: 'sans-serif', tags: ['brutal', 'heavy'] },
  { family: 'Public Sans', category: 'sans-serif', tags: ['minimal', 'clean'] },
  { family: 'Space Grotesk', category: 'sans-serif', tags: ['tech', 'modern'] },
  { family: 'Syne', category: 'sans-serif', tags: ['weird', 'modern'] },
  { family: 'Fraunces', category: 'serif', tags: ['quirky', 'elegant'] },
  { family: 'Manrope', category: 'sans-serif', tags: ['clean', 'geometric'] },
  { family: 'Red Rose', category: 'display', tags: ['elegant', 'romantic'] },
  { family: 'Grenze Gotisch', category: 'display', tags: ['gothic', 'brutal'] },
  { family: 'Goldman', category: 'display', tags: ['cyber', 'gaming'] },
  { family: 'DotGothic16', category: 'sans-serif', tags: ['retro', 'gaming'] },
  { family: 'Hachi Maru Pop', category: 'display', tags: ['cute', 'playful'] },
  { family: 'Reggae One', category: 'display', tags: ['brutal', 'loud'] },
  { family: 'Stick', category: 'display', tags: ['weird', 'geometric'] },
  { family: 'Kiwi Maru', category: 'serif', tags: ['cute', 'friendly'] },
  { family: 'Dela Gothic One', category: 'display', tags: ['brutal', 'heavy'] },
  { family: 'Zen Dots', category: 'display', tags: ['cyber', 'futuristic'] },
  { family: 'Train One', category: 'display', tags: ['weird', 'retro'] },
  { family: 'Turret Road', category: 'sans-serif', tags: ['cyber', 'tech'] },
  { family: 'Michroma', category: 'sans-serif', tags: ['cyber', 'futuristic'] },
  { family: 'Quantico', category: 'sans-serif', tags: ['tech', 'stencil'] },
  { family: 'Ropa Sans', category: 'sans-serif', tags: ['minimal', 'tech'] },
  { family: 'Bruno Ace', category: 'display', tags: ['cyber', 'gaming'] },
  { family: 'Monofett', category: 'display', tags: ['weird', 'monospace'] },
  { family: 'Bungee', category: 'display', tags: ['brutal', 'loud'] },
  { family: 'Bungee Shade', category: 'display', tags: ['retro', 'loud'] },
  { family: 'Bungee Hairline', category: 'display', tags: ['minimal', 'thin'] },
  { family: 'Rubik Glitch', category: 'display', tags: ['weird', 'cyber'] },
  { family: 'Rubik Beastly', category: 'display', tags: ['weird', 'loud'] },
  { family: 'Rubik Puddles', category: 'display', tags: ['weird', 'fluid'] },
  { family: 'Rubik Iso', category: 'display', tags: ['weird', 'geometric'] },
  { family: 'Rubik Microbe', category: 'display', tags: ['weird', 'organic'] },
];

export const PRESET_TEXTS = [
  "The quick brown fox jumps over the lazy dog.",
  "Pack my box with five dozen liquor jugs.",
  "Sphinx of black quartz, judge my vow.",
  "Visual aesthetics are very important.",
  "Infinite scroll is the doom of productivity.",
  "Aesthetics > Functionality (sometimes).",
  "React + TypeScript + Tailwind = ❤️"
];